# Generated by Django 5.1.2 on 2024-11-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('horario', models.TimeField()),
                ('disponibilidad', models.IntegerField()),
            ],
            options={
                'db_table': 'vuelos',
            },
        ),
    ]
